version: '3.5'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: "mysql"
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crudrest
      - MYSQL_USER=simanta
      - MYSQL_PASSWORD=password
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mysql
    container_name: spring-boot-rest-api
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=3306
      - DB_NAME=crudrest
      - DB_HOST=mysql
      - MYSQL_USER=simanta
      - MYSQL_USER_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - mysql